/* Auto-generated by tools/png_to_tiled_map.py */
/* Source image: ../CrabSCV/Graphics/Source/Background.png */
/* Tilesheet: crab_bg_tiles.png */

const int crab_bg_layout_map[] = {
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
    2, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0,
    0, 0, 5, 0, 0, 0, 0, 6, 7, 8, 0, 0, 9, 10, 0,
    0, 11, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 14,
    0, 0, 0, 0, 15, 0, 0, 0, 16, 17, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 18, 0, 0, 0, 0, 0, 0, 0, 19, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20,
    13, 0, 0, 0, 0, 0, 0, 11, 21, 22, 0, 0, 0, 0, 0,
    0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 23, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 27, 35, 36, 26, 27,
};

const int crab_bg_layout_map_width = 15;
const int crab_bg_layout_map_height = 12;
const int crab_bg_layout_tile_width = 16;
const int crab_bg_layout_tile_height = 16;
const int crab_bg_layout_unique_tile_count = 37;
